// @dart=3.12

class NotionSetupOptions {
  const NotionSetupOptions({
    this.dataSourceId = '',
    this.qaUserId = '',
    this.productDomain,
    this.statusEquals = 'Ready to Test',
    this.statusPropertyName = 'Status',
    this.productPropertyName = 'Product domain',
    this.qaPropertyName = 'QA',
  });

  final String dataSourceId;
  final String qaUserId;
  final String? productDomain;
  final String statusEquals;
  final String statusPropertyName;
  final String productPropertyName;
  final String qaPropertyName;
}

Map<String, String> generateNotionReadyToTestFiles({
  required String packageName,
  required String packageLibPath,
  required NotionSetupOptions notion,
}) {
  final p = packageName;
  final lp = packageLibPath;

  return {
    'notion_ready_to_test_defaults.dart': '''
// Generated by qa_bug_session setup — Notion filter labels (no secrets).
import 'package:qa_bug_session/notion/notion.dart';

const notionReadyToTestDefaults = ReadyToTestSetupDefaults(
  statusEquals: '${_escapeDart(notion.statusEquals)}',
  statusPropertyName: '${_escapeDart(notion.statusPropertyName)}',
  productPropertyName: '${_escapeDart(notion.productPropertyName)}',
  qaPropertyName: '${_escapeDart(notion.qaPropertyName)}',
);
''',
    'notion_ready_to_test_storage.dart': '''
// Generated by qa_bug_session setup — secure Notion token + connection.
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:qa_bug_session/notion/notion.dart';

import 'notion_ready_to_test_defaults.dart';

const _storage = FlutterSecureStorage();

const _keyToken = 'ready_to_test_notion_token';
const _keyDataSource = 'ready_to_test_data_source_id';
const _keyQaUser = 'ready_to_test_qa_user_id';
const _keyProduct = 'ready_to_test_product_domain';

final notionReadyToTestStore = _NotionReadyToTestSecureStore();

class _NotionReadyToTestSecureStore implements ReadyToTestCredentialsStore {
  @override
  Future<void> clear() async {
    await _storage.delete(key: _keyToken);
    await _storage.delete(key: _keyDataSource);
    await _storage.delete(key: _keyQaUser);
    await _storage.delete(key: _keyProduct);
  }

  @override
  Future<ReadyToTestConnection?> read() async {
    final token = await _storage.read(key: _keyToken);
    if (token == null || token.isEmpty) {
      return null;
    }
    final dataSourceId = await _storage.read(key: _keyDataSource);
    final qaUserId = await _storage.read(key: _keyQaUser);
    final product = await _storage.read(key: _keyProduct);

    return ReadyToTestConnection(
      token: token,
      dataSourceId: dataSourceId ?? '',
      qaUserId: qaUserId ?? '',
      productDomain: product?.isEmpty ?? true ? null : product,
      statusEquals: notionReadyToTestDefaults.statusEquals,
      statusPropertyName: notionReadyToTestDefaults.statusPropertyName,
      productPropertyName: notionReadyToTestDefaults.productPropertyName,
      qaPropertyName: notionReadyToTestDefaults.qaPropertyName,
    );
  }

  @override
  Future<void> write(ReadyToTestConnection connection) async {
    await _storage.write(key: _keyToken, value: connection.token);
    await _storage.write(
      key: _keyDataSource,
      value: connection.dataSourceId,
    );
    await _storage.write(key: _keyQaUser, value: connection.qaUserId);
    await _storage.write(
      key: _keyProduct,
      value: connection.productDomain ?? '',
    );
  }
}
''',
    'notion_ready_to_test_host.dart': '''
// Generated by qa_bug_session setup — Ready to Test lives on the BugSession FAB panel.
import 'package:flutter/widgets.dart';

Widget wrapReadyToTestTools({required Widget child}) => child;
''',
  };
}

String _escapeDart(String value) {
  return value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}
